name: CI
on: [push]
env:
  JAVA_VERSION: 11
  SPRING_PROFILES_ACTIVE: ci
jobs:
  mvnw:
    strategy:
    runs-on: ubuntu-latest
    name: java-${{ matrix.java }} just build with mvnw maven wrapper
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: |
          ~/.m2
          ~/.npm
          ~/.gradle
          ~/.docker
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-npm-${{ hashFiles('**/pom.xml') }}
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - run: command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
    - run: cd $GITHUB_WORKSPACE && ./mvnw
  step-0-getting-started:
    strategy:
    runs-on: ubuntu-latest
    name: java-${{ matrix.java }} step-0-getting-started
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: |
          ~/.m2
          ~/.npm
          ~/.gradle
          ~/.docker
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-npm-${{ hashFiles('**/pom.xml') }}
    - uses: actions/setup-node@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - run: command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
    - run: sudo apt-get install -y httpie curl jq
    - run: npm i -g wait-port
    - run: cd $GITHUB_WORKSPACE && ./mvnw -P production -f step-0-getting-started package spring-boot:build-image docker-compose:up
    #- run: ( bash $GITHUB_WORKSPACE/step-0-application-without-security/target/*jar --spring.profiles.active=ci & ) || echo ...
    - run: while [[ ! 200 -eq `curl -s -o /dev/null -w "%{http_code}" 0:8080/actuator/health` ]] ; do sleep 1s ; echo -n '.' ; done
    - run: wait-port 8080
    - run: http get :8080
    - run: curl 0:8080
    - run: http --ignore-stdin post :8080/actuator/shutdown
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f step-0-getting-started docker-compose:down
